### PR TITLE
Fix links in icon menu

### LINKED ISSUE #236: PX Blue icons Iconography detail usage and instructions link verbiage all display visit our github
#### Describe the bug
Each tab for px blue icon details has the same verbiage "For detailed usage and installation instructions, visit our GitHub"
#### What is the expected behavior?
Verbiage to for svg and component to reflect NPM

#### What are the steps to reproduce?
1. Go to https://px-blue.github.io/style/iconography?icon=Asparagus
2. Click on github link from each tab, SVG and Component
#### Screenshots or links to minimum reproduction example

image

### PR DESCRIPTION
**Pull request by huayunh**
Fixes #236

### CODE REVIEW

File: src/app/components/icons/IconMenu.tsx [hunk 1]
```diff
@@ -64,7 +64,7 @@ const useStyles = makeStyles((theme: Theme) =>
 );
 
 const instructionLinks = {
-    icons: 'https://github.com/pxblue/icons',
+    iconFont: 'https://github.com/pxblue/icons#using-the-icon-font-in-your-application',
```
Comment (joebochill) [inline src/app/components/icons/IconMenu.tsx:67]: Should we make this one an NPM link too for consistency? https://www.npmjs.com/package/@pxblue/icons
