### PR TITLE
Use clsx; fix double selection error

### LINKED ISSUE #276: Iconography page selects both apple icons
#### Describe the bug

The iconography page selects all icons under the same name when there are dup names

#### What is the expected behavior?

It should select icons with only the correct family

#### What are the steps to reproduce?
1. Go to https://px-blue.github.io/style/iconography?icon=Apple
2. Observe that Material-UI's Apple and PX Blue's Apple both get selected.

#### Screenshots or links to minimum reproduction example
image

#### Environment

		
-- Saint Joseph

### PR DESCRIPTION
**Pull request by huayunh**
Fixes #276

Use `clsx` because I saw this in the source code:
image

### CODE REVIEW

File: src/app/components/icons/IconCard.tsx [hunk 1]
```diff
@@ -39,7 +40,7 @@ export const IconCard: React.FC<IconCardProps> = (props): JSX.Element => {
 
     const { component: Component, name, showLabel, style, selected, iconSize, className } = props;
     return (
-        <div className={`${classes.wrapper} ${selected ? classes.selected : ''} + ${className}`} style={style}>
+        <div className={clsx(classes.wrapper, { [classes.selected]: selected }, className)} style={style}>
```
Comment (joebochill) [inline src/app/components/icons/IconCard.tsx:43]: I actually saw a couple instances where we were using the `+` inside of a template literal. You may want to do a quick sweep and see if you can find any more.

File: src/app/components/icons/IconBrowser.tsx [hunk 2]
```diff
@@ -333,7 +333,8 @@ export const IconBrowser: React.FC = (): JSX.Element => {
                                                             selected={
                                                                 focusedIcon &&
                                                                 getMuiIconName(focusedIcon.name) ===
-                                                                    getMuiIconName(icon.name)
+                                                                    getMuiIconName(icon.name) &&
```
Comment (joebochill) [inline src/app/components/icons/IconBrowser.tsx:336]: You probably also need to add a param to the query string for which icon class (material or blue) the icon is. Otherwise, we can never deep link to the MUI apple icon.

Comment (joebochill) [reply src/app/components/icons/IconBrowser.tsx:336]: We can default to either one if none is specified.

Comment (huayunh) [reply src/app/components/icons/IconBrowser.tsx:348]: My implementation: 

`icon=Apple&isMaterial=` | `true` | `false` | `asdf` | _none_
-|-|-|-|-
PX Blue Apple |                 | selected | selected | selected
Material Apple | selected |                |                 | 

`icon=Apps&isMaterial=` | `true` | `false` | `asdf` | _none_
-|-|-|-|-
Material Apps | selected |                |                 | selected

**Review by joebochill — APPROVED** [review]
